### PR TITLE
Beginning of Cargo Apron. Untextured; need UV MAPPED.

### PR DESCRIPTION
**Pull request by legoboyvdlp**
@mherweg @IAHM-COL 
Here's my first four models.
ANA Hangar
Small building
Smaller building
Square Warehouse

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Thanks, @mherweg :)

**Comment by mherweg** [comment]
you added ALL project3000 models (104 files) to this repo ?  :-(  why?
don't you think it is a good idea to avoid redundancy ?

https://github.com/legoboyvdlp/RJBB-fg-CustomScenery/commit/fd9e90a8ea3599eb5fe9f45378813e6a3e09f8ff

there's a jet blast shield in the water.

**Comment by legoboyvdlp** [comment]
I did? Oops, mistake.
I just meant to add the ones I used.
I'll look at the blast deflector, but it shouldn't be in the water.

**Comment by IAHM-COL** [comment]
Oops!
That's a bad mistake lego.
I talked you before about redundancy in git repos. Is unnecessary. If the
project 3000 already exist, we dont need full copy of that here.
(it just bloats the repo)

Now the problem is... Removing a file from a repository is impossible with
one exception. Git history rewrite.

@ALL
I suggest we do rewrite history in this repo to kick the unnecessary files
out? If you guys want I take that dishonorable task, and git push force a
correct version. From that point you guys would need to reclone, or
something alike.

Other option is leave with the unnecessarily bloated repo

I say, option A is better,
Let me know.

**Comment by legoboyvdlp** [comment]
I don't see any blast deflector in the water.
But I fixed the P3000 models.

**Comment by legoboyvdlp** [comment]
All I actually put in was the thumbnails; it wasn't the models. It was just the thumbnails which actually got in. Maybe some textures too.

**Comment by legoboyvdlp** [comment]
@mherweg see my other PR; it removes the unnecesary files. They were indeed just .pngs.

**Comment by IAHM-COL** [comment]
no. its not the thumbnails. Why do we need all the shared models of Project 3000 here?

**Comment by legoboyvdlp** [comment]
We don't. The only .ac files which were added in this PR were 6 P3000 and 5 I made myself.
You see, it makes it easier for people; not having to download 104 models to get 6.

**Comment by legoboyvdlp** [comment]
See my new PR, #4 removes thumbnails.

**Comment by IAHM-COL** [comment]
that doesnt remove the files from the git repo. See my new master suggestion.

**Pull request merged**
